![logo_ironhack_blue 7](https://user-images.githubusercontent.com/23629340/40541063-a07a0a8a-601a-11e8-91b5-2f13e4e6b441.png)

# Lab | Random Forests

For this lab, you will be using the CSV files provided in the `files_for_lab` folder.

### Instructions

- Apply the Random Forests algorithm but this time only by upscaling the data using `SMOTE`.
- Note that since `SMOTE` works on numerical data only, we will first encode the categorical variables in this case.

In [22]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [23]:
numerical = pd.read_csv('C:/Users/aguva/Ironhack/Week_18/lab-random-forests/files_for_lab/numerical.csv')
categorical = pd.read_csv('C:/Users/aguva/Ironhack/Week_18/lab-random-forests/files_for_lab/categorical.csv')
targets = pd.read_csv('C:/Users/aguva/Ironhack/Week_18/lab-random-forests/files_for_lab/target.csv')
data = pd.concat([numerical, categorical, targets], axis = 1)

In [28]:
data.head()

,TCODE,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,...,311,312,313,314,315,316,317,318,TARGET_B,TARGET_D
0,0,60.000000,5,9,0,0,39,34,18,10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0.0
1,1,46.000000,6,9,16,0,15,55,11,6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0
2,1,61.611649,3,1,2,0,20,29,33,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
3,0,70.000000,1,4,2,0,23,14,31,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
4,0,78.000000,3,2,60,1,28,9,53,26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0

In [25]:
encoder = OneHotEncoder(drop='first').fit(categorical)
encoded_categorical = encoder.transform(categorical).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical)

In [26]:
data = pd.concat([numerical, encoded_categorical, targets], axis = 1)

In [27]:
data.head()

,TCODE,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,...,311,312,313,314,315,316,317,318,TARGET_B,TARGET_D
0,0,60.000000,5,9,0,0,39,34,18,10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0.0
1,1,46.000000,6,9,16,0,15,55,11,6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0
2,1,61.611649,3,1,2,0,20,29,33,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
3,0,70.000000,1,4,2,0,23,14,31,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
4,0,78.000000,3,2,60,1,28,9,53,26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0

In [ ]:
data.info()

In [29]:
regression_target = data['TARGET_D']
# data.head()
y = data['TARGET_B']
X = data.drop(['TARGET_B'], axis = 1)

X.columns = X.columns.astype(str)

In [30]:
data['TARGET_B'].value_counts()

0    90569
1     4843
Name: TARGET_B, dtype: int64

In [31]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_sm, y_sm = smote.fit_resample(X, y)
y_sm.value_counts()

0    90569
1    90569
Name: TARGET_B, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.25, random_state=0)

In [35]:
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [37]:
print(rf_classifier.score(X_test, y_test))

0.9982334106216186